# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- script: |
    git clone https://github.com/ZorrillosDev/watchit-desktop.git
    cd watchit-desktop
    npm install
    npm run build
     npm run package:win

  displayName: 'Build watchit'
