# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone $(WATCHIT_REPO_URL)
      cd watchit-desktop
      npm install
      npm run package:win
      pwd
      ls -la


- task: CopyFiles@2
  inputs:
    SourceFolder: 'watchit-desktop\release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Build watchit'
